import type { Metadata } from "next";
import "./globals.css";
import "./application.css";
import { Providers } from "@/app/providers";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Providers>
      <body>
      {children}
      <Toaster toastOptions={{ style: { borderRadius: '1000px' } }}/>
      </body>
    </Providers>
    </html>
  );
}
